version: 1.2
workflows:
 - name: BS_Fetch_to_Dir
   subclass: WDL
   primaryDescriptorPath: /workflows/bs_fetch_to_dir.wdl
   testParameterFiles:
    - empty.json
   authors:
    - name: Kutluhan Incekara
      email: kutluhan.incekara@ct.gov