version: 1.2
workflows:
 - name: SRA_prep
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_sra_prep.wdl
   testParameterFiles:
    - /empty.json

 - name: REDCap_prep
   subclass: WDL
   primaryDescriptorPath: /workflows/wf_redcap_prep.wdl
   testParameterFiles:
    - /empty.json
    